### ISSUE TITLE
how to view the pokemon?

### ISSUE THREAD

**Issue by setanindo** [Fiaxhs/pgmap#11]
im see its just view map, pokemon spawn not included?

**Comment by Fiaxhs** [comment]
Click on the map, a blue circle should appear soon after, it's scanning the location for pokémons. (~10s to scan)

**Comment by setanindo** [comment]
hii fiaxhs thanks for replying,
the blue circle and scaning not showing, im miss something?

**Comment by Fiaxhs** [comment]
Hi @setanindo, did the `npm install` went fine? It seems that socketio isn't up.
Could you provide me the log of both `npm install` then `npm run start`? Use https://gist.github.com/ to paste them

**Comment by setanindo** [comment]
ah thanks fiaxhs its work great, im missing npm
thanks
