### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by HasanY1989** [Fiaxhs/pgmap#14]
Sorry if this goes to the wrong section !

However my Question is. 

Can i host this and make a domain ? and how?

Atm im using ngrok to host it on my computer.

**Comment by BenoitZugmeyer** [comment]
Try [heroku](https://devcenter.heroku.com/articles/getting-started-with-nodejs#introduction) or ask google.

**Comment by HasanY1989** [comment]
Ty for the answer mate!
Yea, i am googling it, and Ngrok is what im comming up with xD 
As for Heroku I understood by other people, its not possible anymore since its blocked by niantic
