### ISSUE TITLE
multiple workers

### ISSUE THREAD

**Issue by vinsilsim** [Fiaxhs/pgmap#17]
can put many workers to get faster?

**Comment by HasanY1989** [comment]
Its not added yet

**Comment by vinsilsim** [comment]
bad :(

**Comment by florentsolt** [comment]
😎🍿

**Comment by BenoitZugmeyer** [comment]
:trollface: 👏

**Comment by Fiaxhs** [comment]
Hey guys, this is an open source project, feel free to fork and contribute :)
