### ISSUE TITLE
[Multiple Accounts] Format

### ISSUE THREAD

**Issue by vinsilsim** [Fiaxhs/pgmap#29]
which format to multiple accounts?

**Comment by Fiaxhs** [comment]
The pull request is now merged, take a look at the [config.js.sample](https://github.com/Fiaxhs/pgmap/blob/f8fcef4fe23f0fe477e2c90d1f24b5c6ada337dc/config.js.sample)

Multiple accounts should look like this

``` javascript
    accounts: [
        {
            username: 'user1',
            password: 'password1',
            provider: 'google or ptc'
        },
        {
            username: 'user2',
            password: 'password2',
            provider: 'google or ptc'
        },
    ],
```

**Comment by vinsilsim** [comment]
@Fiaxhs thank you bro!
