### ISSUE TITLE
Hey mate

### ISSUE THREAD

**Issue by HasanY1989** [Fiaxhs/pgmap#5]
So this is only the style or does it also work as pokevision?

**Comment by Fiaxhs** [comment]
Hey, the goal is to have a pokevison replacement, so yeah it works like
pokevison :)

Keep in mind that it's a work in progress!

**Comment by HasanY1989** [comment]
Mans thats aswome ! 

I will contribute as much as I can ! 

However im not that good of a coder yet xD 

Btw i did everything as instructed and when i run npm run, it wont start it, says node js is and thats it xD ?

**Comment by HasanY1989** [comment]
@Fiaxhs 
Just added the pic for you to see. 
http://oi64.tinypic.com/96ydtl.jpg

**Comment by HasanY1989** [comment]
Lso when i write npm install, som errors comes xD?
http://oi64.tinypic.com/egztko.jpg

**Comment by Fiaxhs** [comment]
It's:
npm run start

Anyway, niantic has changed it's protocol yesterday, so all non official
projects like this one are currently broken.

**Comment by HasanY1989** [comment]
@Fiaxhs 
Thank you for the fast reply.
Yea, I know the API issuc, i run The POKOMAP from AAAAAHAAA, and it seems also good for personal use, however, i really liked pokesvision. 

I want to run it, cuz i want to see the style etc etc. 
I wrote npm run start

and this was the outcome: 
http://oi64.tinypic.com/97s5yr.jpg

Yet again ty for the fast answer !

**Comment by Fiaxhs** [comment]
By looking at the npm install errors, it seems that you must install git: https://git-scm.com/download/win default options should do it.
Open a new command.exe after install, it may not be detected as installed otherwise.

**Comment by HasanY1989** [comment]
its installed. 
And i did npm install just to be sure
and then npm run start.. witrh closed cmd and so on, still gives me the same erros, says i need to contact you. any idea what i might do wrong ? 

Downloaded in and installed the latest (2.9.2) 64-bit version

**Comment by Fiaxhs** [comment]
What's the result of npm install? Any errors?

**Comment by HasanY1989** [comment]
Yea, I got no idea what it is tho. 
SS from the error. 
http://oi63.tinypic.com/23qxcw2.jpg

**Comment by Fiaxhs** [comment]
Well if the install fails, it can't run.
The red line in your last screenshot gives you instructions, I advise you to follow them then try npm install again.
Untill npm install fails, you won't be able to run pgmap

**Comment by HasanY1989** [comment]
Damn xD 
In the instructions it says, downloade framwork 2.0 which is the old vision (i did) , then down load mircosft studio 2005 which i also did, or move it. 

I cant even install framwork when i get it, i think its to of an old vision? 

I could install npm in pokemon go map tho, you think i might need to get better then 2.0? framwork
