### ISSUE TITLE
Is the project still going, api is fixed?

### ISSUE THREAD

**Issue by HasanY1989** [Fiaxhs/pgmap#8]
Is this still going, the API got fixed :-)

**Comment by Fiaxhs** [comment]
Hey @HasanY1989  please refrain from opening multiple issues :)

The api has been fixed, yet this project relies on the node port, ( see https://github.com/Armax/Pokemon-GO-node-api ) they need to update it, then pgmap should work again. 

You can follow the update here: https://github.com/Armax/Pokemon-GO-node-api/issues/205

Once it's been updated, you should be able to run `npm update` then `npm run start` and everything should be working.

**Comment by HasanY1989** [comment]
Sweet ty for the answer will close this :-)
